In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.22.0


In [4]:
print(np.show_config())

openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', 

In [5]:
a = np.random.random((2,3,5))

In [50]:
print(a)
print (a.ndim)

[[[0.51153727 0.67441124 0.34391563 0.78449134 0.79408641]
  [0.10174574 0.86635798 0.67288566 0.7136223  0.68392048]
  [0.71185468 0.62424147 0.0107924  0.0743098  0.32381001]]

 [[0.14254587 0.37350551 0.34880453 0.61493384 0.38824756]
  [0.87599038 0.57563423 0.55811578 0.13171443 0.51240494]
  [0.87288257 0.26720253 0.29989189 0.52578747 0.93273709]]]
3


In [22]:
a2 = np.random.randint(0, 100, size=(2, 3, 5))

In [46]:
print(a2)

[[[22 78  7  4 13]
  [25 14 48 49 32]
  [25  2 29 14 22]]

 [[76 54 47 94 16]
  [96 20 82 10 86]
  [39 14 22 35 45]]]


In [26]:
b = np.ones((5,2,3))

In [27]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [33]:
sizea = a.size      #llamando desde el argumento 

In [37]:
sizeb = b.size

In [35]:
print(np.size(a))   #Llamado desde la funcion

30


In [38]:
if sizea == sizeb:
    print("a y b son iguales")

a y b son iguales


Respuesta pregunta 8:

No, porque a y b tienen diferente forma. 
    


In [52]:
c = np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [53]:
a + c

array([[[1.51153727, 1.67441124, 1.34391563, 1.78449134, 1.79408641],
        [1.10174574, 1.86635798, 1.67288566, 1.7136223 , 1.68392048],
        [1.71185468, 1.62424147, 1.0107924 , 1.0743098 , 1.32381001]],

       [[1.14254587, 1.37350551, 1.34880453, 1.61493384, 1.38824756],
        [1.87599038, 1.57563423, 1.55811578, 1.13171443, 1.51240494],
        [1.87288257, 1.26720253, 1.29989189, 1.52578747, 1.93273709]]])