In [3]:
import numpy as np

In [4]:
np.__version__

'1.22.3'

In [5]:
np.show_config()

openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', 

In [6]:
a=np.random.random((2,3,5))
print(a)

[[[0.38082274 0.46546576 0.76503336 0.1171072  0.67377173]
  [0.76374812 0.28829055 0.88128448 0.23490648 0.86973389]
  [0.59203327 0.1723532  0.76236199 0.12615355 0.29098819]]

 [[0.95746267 0.89894425 0.43502967 0.82291602 0.92208747]
  [0.76127909 0.57261203 0.74085363 0.02222116 0.42054373]
  [0.27331586 0.38397395 0.95491801 0.4136418  0.12679316]]]


In [7]:
b=np.ones((5,3,2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [8]:
np.size(a)

30

In [9]:
np.size(b)

30

In [10]:
if np.size(a) == np.size(b):
    print("Same size")
else:
    print("Not same size")

Same size


In [11]:
c= a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [12]:
c= np.transpose(b)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [13]:
d= a + c
print(d)

[[[1.38082274 1.46546576 1.76503336 1.1171072  1.67377173]
  [1.76374812 1.28829055 1.88128448 1.23490648 1.86973389]
  [1.59203327 1.1723532  1.76236199 1.12615355 1.29098819]]

 [[1.95746267 1.89894425 1.43502967 1.82291602 1.92208747]
  [1.76127909 1.57261203 1.74085363 1.02222116 1.42054373]
  [1.27331586 1.38397395 1.95491801 1.4136418  1.12679316]]]


In [14]:
print(a)
print("-----------------"*4)
print(d)

d[0,0,0]

[[[0.38082274 0.46546576 0.76503336 0.1171072  0.67377173]
  [0.76374812 0.28829055 0.88128448 0.23490648 0.86973389]
  [0.59203327 0.1723532  0.76236199 0.12615355 0.29098819]]

 [[0.95746267 0.89894425 0.43502967 0.82291602 0.92208747]
  [0.76127909 0.57261203 0.74085363 0.02222116 0.42054373]
  [0.27331586 0.38397395 0.95491801 0.4136418  0.12679316]]]
--------------------------------------------------------------------
[[[1.38082274 1.46546576 1.76503336 1.1171072  1.67377173]
  [1.76374812 1.28829055 1.88128448 1.23490648 1.86973389]
  [1.59203327 1.1723532  1.76236199 1.12615355 1.29098819]]

 [[1.95746267 1.89894425 1.43502967 1.82291602 1.92208747]
  [1.76127909 1.57261203 1.74085363 1.02222116 1.42054373]
  [1.27331586 1.38397395 1.95491801 1.4136418  1.12679316]]]


1.380822736160025

In [15]:
e=a*c
print(e)
print(e[1,2,4])

[[[0.38082274 0.46546576 0.76503336 0.1171072  0.67377173]
  [0.76374812 0.28829055 0.88128448 0.23490648 0.86973389]
  [0.59203327 0.1723532  0.76236199 0.12615355 0.29098819]]

 [[0.95746267 0.89894425 0.43502967 0.82291602 0.92208747]
  [0.76127909 0.57261203 0.74085363 0.02222116 0.42054373]
  [0.27331586 0.38397395 0.95491801 0.4136418  0.12679316]]]
0.12679316436991617


In [16]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max,d_min,d_mean)

1.957462673129045 1.022221156262499 1.5363548998783576


In [17]:
f=np.empty((2,3,5))
print(len(d))
shape_d=d.shape



2


In [30]:
for matriz in range(shape_d[0]):
    for vector in range(shape_d[1]):
        for valor in range(shape_d[2]):
            if d[matriz,vector,valor] == d_min:
                f[matriz,vector,valor] = 0
            elif d[matriz,vector,valor] < d_mean:
                f[matriz,vector,valor] = 25
            elif d[matriz,vector,valor] == d_mean:
                f[matriz,vector,valor] = 50
            elif d[matriz,vector,valor] < d_max:
                f[matriz,vector,valor] = 75
            elif d[matriz,vector,valor] == d_max:
                f[matriz,vector,valor] = 100
print (f)

print(type(f[0,0,0]))

[[[ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[100.  75.  25.  75.  75.]
  [ 75.  75.  75.   0.  25.]
  [ 25.  25.  75.  25.  25.]]]
<class 'numpy.float64'>


In [19]:
print(d)
print("-----------------------------------------------------------------")
print(f)

[[[1.38082274 1.46546576 1.76503336 1.1171072  1.67377173]
  [1.76374812 1.28829055 1.88128448 1.23490648 1.86973389]
  [1.59203327 1.1723532  1.76236199 1.12615355 1.29098819]]

 [[1.95746267 1.89894425 1.43502967 1.82291602 1.92208747]
  [1.76127909 1.57261203 1.74085363 1.02222116 1.42054373]
  [1.27331586 1.38397395 1.95491801 1.4136418  1.12679316]]]
-----------------------------------------------------------------
[[[ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[100.  75.  25.  75.  75.]
  [ 75.  75.  75.   0.  25.]
  [ 25.  25.  75.  25.  25.]]]
