#1. Import the NUMPY package under the name np.


In [2]:
import numpy as np

#2. Print the NUMPY version and the configuration.


In [3]:
np.__version__

'1.21.3'

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2, 3, 5))


In [5]:
#4. Print a.

print(a)

[[[0.3986415  0.18936882 0.12361385 0.36588593 0.91352284]
  [0.08438749 0.11708491 0.08673339 0.19758236 0.00895327]
  [0.23833941 0.06591733 0.94967855 0.11483783 0.09410038]]

 [[0.51153684 0.71936704 0.15556593 0.28351401 0.38104111]
  [0.01965208 0.27164629 0.08785118 0.7822625  0.49346368]
  [0.06840939 0.57971196 0.87802421 0.65204048 0.29087566]]]


In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))

In [7]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?

a.size == b.size


True

In [9]:
b.size

30

In [10]:
a.size

30

In [11]:
#8. Are you able to add a and b? Why or why not?

a_b = a + b

#no se pueden sumar porqe no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [12]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
print(c)
#c = np.transpose(b,(1,2,0))
#print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [13]:
c.shape

(2, 3, 5)

In [14]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c
d

#se pueden sumar porque tienen la misma forma

array([[[1.3986415 , 1.18936882, 1.12361385, 1.36588593, 1.91352284],
        [1.08438749, 1.11708491, 1.08673339, 1.19758236, 1.00895327],
        [1.23833941, 1.06591733, 1.94967855, 1.11483783, 1.09410038]],

       [[1.51153684, 1.71936704, 1.15556593, 1.28351401, 1.38104111],
        [1.01965208, 1.27164629, 1.08785118, 1.7822625 , 1.49346368],
        [1.06840939, 1.57971196, 1.87802421, 1.65204048, 1.29087566]]])

In [15]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)

[[[0.3986415  0.18936882 0.12361385 0.36588593 0.91352284]
  [0.08438749 0.11708491 0.08673339 0.19758236 0.00895327]
  [0.23833941 0.06591733 0.94967855 0.11483783 0.09410038]]

 [[0.51153684 0.71936704 0.15556593 0.28351401 0.38104111]
  [0.01965208 0.27164629 0.08785118 0.7822625  0.49346368]
  [0.06840939 0.57971196 0.87802421 0.65204048 0.29087566]]]


In [16]:
print(d)

[[[1.3986415  1.18936882 1.12361385 1.36588593 1.91352284]
  [1.08438749 1.11708491 1.08673339 1.19758236 1.00895327]
  [1.23833941 1.06591733 1.94967855 1.11483783 1.09410038]]

 [[1.51153684 1.71936704 1.15556593 1.28351401 1.38104111]
  [1.01965208 1.27164629 1.08785118 1.7822625  1.49346368]
  [1.06840939 1.57971196 1.87802421 1.65204048 1.29087566]]]


In [17]:
#12. Multiply a and c. Assign the result to e.

e = a * c
e

array([[[0.3986415 , 0.18936882, 0.12361385, 0.36588593, 0.91352284],
        [0.08438749, 0.11708491, 0.08673339, 0.19758236, 0.00895327],
        [0.23833941, 0.06591733, 0.94967855, 0.11483783, 0.09410038]],

       [[0.51153684, 0.71936704, 0.15556593, 0.28351401, 0.38104111],
        [0.01965208, 0.27164629, 0.08785118, 0.7822625 , 0.49346368],
        [0.06840939, 0.57971196, 0.87802421, 0.65204048, 0.29087566]]])

In [18]:
#13. Does e equal to a? Why or why not?

a == e

#son iguales de tamaño porque tienen la misma forma

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [19]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)


1.94967854620955
1.0089532724484163
1.3374536741013434


In [20]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2, 3, 5))
f

array([[[0.3986415 , 0.18936882, 0.12361385, 0.36588593, 0.91352284],
        [0.08438749, 0.11708491, 0.08673339, 0.19758236, 0.00895327],
        [0.23833941, 0.06591733, 0.94967855, 0.11483783, 0.09410038]],

       [[0.51153684, 0.71936704, 0.15556593, 0.28351401, 0.38104111],
        [0.01965208, 0.27164629, 0.08785118, 0.7822625 , 0.49346368],
        [0.06840939, 0.57971196, 0.87802421, 0.65204048, 0.29087566]]])

In [41]:
'''
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
'''

#np.where(atriz >= 7, 'C', np.where(matriz == 0, 'A', 'B'))
f = np.where((d > d_min) & (d < d_mean), 25,
         np.where((d > d_mean) & (d < d_max), 75, 
                   np.where(d == d_mean, 50, 
                             np.where(d == d_min, 0, 
                                       np.where(d == d_max, 100,
                                               100)))))

In [42]:
#17. Print d and f. Do you have your expected f?
print(f)

[[[ 75  25  25  75  75]
  [ 25  25  25  25   0]
  [ 25  25 100  25  25]]

 [[ 75  75  25  25  75]
  [ 25  25  25  75  75]
  [ 25  75  75  75  25]]]


In [45]:
'''#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:'''

g = np.where(f == 0, 'A',
        np.where(f == 25, 'B',
                np.where(f == 50, 'C',
                        np.where(f == 75, 'D',
                                np.where(f == 100, 'E',
                                        'E')))))

In [46]:
print(g)

[[['D' 'B' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'A']
  ['B' 'B' 'E' 'B' 'B']]

 [['D' 'D' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'D' 'D' 'B']]]
