### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [2]:
np.__version__

'1.22.3'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a".  Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

### 4. Print a.

In [3]:
a= np.random.random((2,3,5))
a

array([[[0.34744507, 0.12893892, 0.49611525, 0.68595093, 0.38093809],
        [0.87322061, 0.52641428, 0.77925582, 0.25491311, 0.51830706],
        [0.8698612 , 0.86627383, 0.59336454, 0.64289162, 0.94088231]],

       [[0.27826629, 0.69261561, 0.16962819, 0.64218734, 0.78806228],
        [0.9525613 , 0.66399449, 0.959766  , 0.53166565, 0.60798534],
        [0.99859489, 0.31683756, 0.63047685, 0.48556171, 0.65810023]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b" 
### 6. Print b.

In [4]:
b= np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### 7. Do a and b have the same size? How do you prove that in Python code?


In [5]:
# In Python, numpy.size() function count the number of elements along a given axis.
print('numpy method', np.size(a), np.size(b))

cnt_a=0
for i in a:
    for  j in i:
        for k in j:
            cnt_a+=1
cnt_b=0
for i in b:
    for  j in i:
        for k in j:
            cnt_b+=1


print('python method', cnt_a, cnt_b)




numpy method 30 30
python method 30 30


### 8. Are you able to add a and b? Why or why not?


### Those are different-size-matrix,  those cannot add each other. 

In [6]:
c= a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [7]:
c= b.reshape(2,3,5)

In [8]:
print(a.shape,b.shape, c.shape)

(2, 3, 5) (5, 2, 3) (2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [9]:
d=a+c
d
#Can work because now those are same-size-matrix

array([[[1.34744507, 1.12893892, 1.49611525, 1.68595093, 1.38093809],
        [1.87322061, 1.52641428, 1.77925582, 1.25491311, 1.51830706],
        [1.8698612 , 1.86627383, 1.59336454, 1.64289162, 1.94088231]],

       [[1.27826629, 1.69261561, 1.16962819, 1.64218734, 1.78806228],
        [1.9525613 , 1.66399449, 1.959766  , 1.53166565, 1.60798534],
        [1.99859489, 1.31683756, 1.63047685, 1.48556171, 1.65810023]]])

### 11.Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [10]:
print (a,'\n\n--\n\n',d)

[[[0.34744507 0.12893892 0.49611525 0.68595093 0.38093809]
  [0.87322061 0.52641428 0.77925582 0.25491311 0.51830706]
  [0.8698612  0.86627383 0.59336454 0.64289162 0.94088231]]

 [[0.27826629 0.69261561 0.16962819 0.64218734 0.78806228]
  [0.9525613  0.66399449 0.959766   0.53166565 0.60798534]
  [0.99859489 0.31683756 0.63047685 0.48556171 0.65810023]]] 

--

 [[[1.34744507 1.12893892 1.49611525 1.68595093 1.38093809]
  [1.87322061 1.52641428 1.77925582 1.25491311 1.51830706]
  [1.8698612  1.86627383 1.59336454 1.64289162 1.94088231]]

 [[1.27826629 1.69261561 1.16962819 1.64218734 1.78806228]
  [1.9525613  1.66399449 1.959766   1.53166565 1.60798534]
  [1.99859489 1.31683756 1.63047685 1.48556171 1.65810023]]]


In [30]:
### 'a' es una matriz que guardo datos aleatorios, 'b' es una matriz que guarda solo unos, c que es la restructura de 
### 'b' que se sumo a 'a' para formar d, entonces la diferencia entre 'a' y 'd' es de 1 en todos sus digitos. 

### 12. Multiply a and c. Assign the result to e.


In [11]:
e= a*c
e

array([[[0.34744507, 0.12893892, 0.49611525, 0.68595093, 0.38093809],
        [0.87322061, 0.52641428, 0.77925582, 0.25491311, 0.51830706],
        [0.8698612 , 0.86627383, 0.59336454, 0.64289162, 0.94088231]],

       [[0.27826629, 0.69261561, 0.16962819, 0.64218734, 0.78806228],
        [0.9525613 , 0.66399449, 0.959766  , 0.53166565, 0.60798534],
        [0.99859489, 0.31683756, 0.63047685, 0.48556171, 0.65810023]]])

### 13. Does e equal to a? Why or why not?

In [14]:
print(e, '\n\n\n', a)

[[[0.34744507 0.12893892 0.49611525 0.68595093 0.38093809]
  [0.87322061 0.52641428 0.77925582 0.25491311 0.51830706]
  [0.8698612  0.86627383 0.59336454 0.64289162 0.94088231]]

 [[0.27826629 0.69261561 0.16962819 0.64218734 0.78806228]
  [0.9525613  0.66399449 0.959766   0.53166565 0.60798534]
  [0.99859489 0.31683756 0.63047685 0.48556171 0.65810023]]] 


 [[[0.34744507 0.12893892 0.49611525 0.68595093 0.38093809]
  [0.87322061 0.52641428 0.77925582 0.25491311 0.51830706]
  [0.8698612  0.86627383 0.59336454 0.64289162 0.94088231]]

 [[0.27826629 0.69261561 0.16962819 0.64218734 0.78806228]
  [0.9525613  0.66399449 0.959766   0.53166565 0.60798534]
  [0.99859489 0.31683756 0.63047685 0.48556171 0.65810023]]]


In [ ]:
## Son iguales, porque e= a*c, c=a+b, e=a*(a+b)...

### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [16]:
d_max= d.max()
d_min= d.min()
d_mean= d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9985948883376308
1.1289389195573345
1.6093692118741048


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [17]:
f= np.empty((2,3,5))
f

array([[[0.34744507, 0.12893892, 0.49611525, 0.68595093, 0.38093809],
        [0.87322061, 0.52641428, 0.77925582, 0.25491311, 0.51830706],
        [0.8698612 , 0.86627383, 0.59336454, 0.64289162, 0.94088231]],

       [[0.27826629, 0.69261561, 0.16962819, 0.64218734, 0.78806228],
        [0.9525613 , 0.66399449, 0.959766  , 0.53166565, 0.60798534],
        [0.99859489, 0.31683756, 0.63047685, 0.48556171, 0.65810023]]])

### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [78]:
#f= np.empty((2,3,5))
print(d_min)
#np.where(condicion(es), if True return, lista a probar)


f= np.where((d==d_min),0, f)
f= np.where((d>d_min)& (d<d_mean),25, f)
f= np.where((d==d_mean), 50, f)
f= np.where((d>d_mean)&(d<d_max),75,f)
f= np.where((d==d_max),100,f)
print(f)

1.1289389195573345
[[[ 25.   0.  25.  75.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  75.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [100.  25.  75.  25.  75.]]]


In [77]:
liss=np.array([[1,2,3,4,5],[6,7,8,9,10]])
liss2= np.array([[11,12,13,14,15],[16,17,18,19,20]])

np.where( (liss>3)&(liss<8), 'zero',liss2 ) #np.where(condicion(es)/if True return/ lista a regresar)

array([['11', '12', '13', 'zero', 'zero'],
       ['zero', 'zero', '18', '19', '20']], dtype='<U11')