### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.20.1


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a=np.random.random((2,3,5))

### 4. Print a.

In [6]:
print(a)

[[[0.86536906 0.26889636 0.33765314 0.85431629 0.9027232 ]
  [0.41219972 0.39808439 0.39367682 0.10567652 0.07136439]
  [0.95436904 0.29776034 0.17684894 0.54595977 0.74403071]]

 [[0.59649355 0.04913538 0.71634206 0.37498136 0.90752449]
  [0.30778352 0.98244473 0.1709661  0.68167958 0.56544941]
  [0.4072355  0.97498309 0.72268754 0.80195143 0.7630969 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. #Assign the array to variable "b"


In [27]:
b=np.ones((5,2,3))

### 6. Print b.


In [28]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 7. Do a and b have the same size? How do you prove that in Python code?



In [10]:
print('Do a and b have the same size?',np.size(a) == np.size(b))

Do a and b have the same size? True


### 8. Are you able to add a and b? Why or why not?

In [12]:
try:
    a+b
except:
    print('No se puede porque no tienen la misma forma')

No se puede porque no tienen la misma forma


### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [35]:
c= np.transpose(b,(1,2,0)) #se ponen las coordenadas de la matriz a 
print(c.shape)

#forma de a (2,3,5)
#forma de b (5,2,3)

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [36]:
d= a+c
print(d)
print('Funciona por ya tienen la misma forma y estructura')

[[[1.86536906 1.26889636 1.33765314 1.85431629 1.9027232 ]
  [1.41219972 1.39808439 1.39367682 1.10567652 1.07136439]
  [1.95436904 1.29776034 1.17684894 1.54595977 1.74403071]]

 [[1.59649355 1.04913538 1.71634206 1.37498136 1.90752449]
  [1.30778352 1.98244473 1.1709661  1.68167958 1.56544941]
  [1.4072355  1.97498309 1.72268754 1.80195143 1.7630969 ]]]
Funciona por ya tienen la misma forma y estructura


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
print(a)

[[[0.86536906 0.26889636 0.33765314 0.85431629 0.9027232 ]
  [0.41219972 0.39808439 0.39367682 0.10567652 0.07136439]
  [0.95436904 0.29776034 0.17684894 0.54595977 0.74403071]]

 [[0.59649355 0.04913538 0.71634206 0.37498136 0.90752449]
  [0.30778352 0.98244473 0.1709661  0.68167958 0.56544941]
  [0.4072355  0.97498309 0.72268754 0.80195143 0.7630969 ]]]


In [38]:
print(d)

[[[1.86536906 1.26889636 1.33765314 1.85431629 1.9027232 ]
  [1.41219972 1.39808439 1.39367682 1.10567652 1.07136439]
  [1.95436904 1.29776034 1.17684894 1.54595977 1.74403071]]

 [[1.59649355 1.04913538 1.71634206 1.37498136 1.90752449]
  [1.30778352 1.98244473 1.1709661  1.68167958 1.56544941]
  [1.4072355  1.97498309 1.72268754 1.80195143 1.7630969 ]]]


#La diferencia es porque a b(matriz) se asigno una matriz de puros 1 y como b(matriz) se convirtio en c(matriz), y d(matriz) es la suma de a+c entonces a a se le sumo lo de b(matriz) que es 1.

### 12. Multiply a and c. Assign the result to e.

In [39]:
e= a*c
print(e)

[[[0.86536906 0.26889636 0.33765314 0.85431629 0.9027232 ]
  [0.41219972 0.39808439 0.39367682 0.10567652 0.07136439]
  [0.95436904 0.29776034 0.17684894 0.54595977 0.74403071]]

 [[0.59649355 0.04913538 0.71634206 0.37498136 0.90752449]
  [0.30778352 0.98244473 0.1709661  0.68167958 0.56544941]
  [0.4072355  0.97498309 0.72268754 0.80195143 0.7630969 ]]]


### 13. Does e equal to a? Why or why not?

In [40]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [42]:
d_max= np.max(d)
d_min= np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9824447294364238
1.0491353781260877
1.5450561112400303


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using np.empty.


In [46]:
f= np.empty((2,3,5))
print(f)

[[[0.86536906 0.26889636 0.33765314 0.85431629 0.9027232 ]
  [0.41219972 0.39808439 0.39367682 0.10567652 0.07136439]
  [0.95436904 0.29776034 0.17684894 0.54595977 0.74403071]]

 [[0.59649355 0.04913538 0.71634206 0.37498136 0.90752449]
  [0.30778352 0.98244473 0.1709661  0.68167958 0.56544941]
  [0.4072355  0.97498309 0.72268754 0.80195143 0.7630969 ]]]


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f. If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. If a value equals to d_mean, assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f for d_min in d. Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the following values: 0, 25, 50, 75, and 100. Note: you don't have to use Numpy in this question. """



In [ ]:
#d > d_min  o  d < d_mean = 25
#d > d_mean  o  d < d_max = 75
#d = d_mean = 50  o

In [50]:
f=np.where(d == d_min,0, np.where((d > d_min) & (d < d_mean),25, np.where (d == d_mean,50, np.where((d > d_mean) & (d < d_max),75, 100))))

In [51]:
print(f)

[[[ 75  25  25  75  75]
  [ 25  25  25  25  25]
  [ 75  25  25  75  75]]

 [[ 75   0  75  25  75]
  [ 25 100  25  75  75]
  [ 25  75  75  75  75]]]


In [56]:
for ind, sub_arr in enumerate (d):
    #print(ind,sub_arr)
    for ind_sub, sub_sub_arr in enumerate(sub_arr):
     #   print(ind_sub,sub_sub_arr)
      #  print()
        for ind_sub_sub, element in enumerate(sub_sub_arr):
       #     print(ind_sub_sub, element)
            if element==d_min:
                f[ind][ind_sub][ind_sub_sub]=0
            elif element > d_min and element < d_mean:
                f[ind][ind_sub][ind_sub_sub]=25
            elif element == d_mean:
                f[ind][ind_sub][ind_sub_sub]=50
            elif element > d_mean and element < d_max:
                f[ind][ind_sub][ind_sub_sub]=75
            else:
                f[ind][ind_sub][ind_sub_sub]=100
print(f)
    

[[[ 75  25  25  75  75]
  [ 25  25  25  25  25]
  [ 75  25  25  75  75]]

 [[ 75   0  75  25  75]
  [ 25 100  25  75  75]
  [ 25  75  75  75  75]]]


### 17. Print d and f. Do you have your expected f? For instance, if your d is: array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

   [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
    [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
    [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
Your f should be: array([[[ 75., 75., 75., 25., 75.], [ 75., 75., 25., 25., 25.], [ 75., 25., 75., 75., 75.]],

   [[ 25.,  25.,  25.,  25., 100.],
    [ 75.,  75.,  75.,  75.,  75.],
    [ 25.,  75.,   0.,  75.,  75.]]])
"""



### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be: array([[[ 'D', 'D', 'D', 'B', 'D'], [ 'D', 'D', 'B', 'B', 'B'], [ 'D', 'B', 'D', 'D', 'D']],

   [[ 'B',  'B',  'B',  'B',  'E'],
    [ 'D',  'D',  'D',  'D',  'D'],
    [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question. ""

In [57]:
g = np.empty((2,3,5), dtype="O")

for ind, sub_arr in enumerate (d):
    #print(ind,sub_arr)
    for ind_sub, sub_sub_arr in enumerate(sub_arr):
     #   print(ind_sub,sub_sub_arr)
      #  print()
        for ind_sub_sub, element in enumerate(sub_sub_arr):
       #     print(ind_sub_sub, element)
            if element==d_min:
                f[ind][ind_sub][ind_sub_sub]='A'
            elif element > d_min and element < d_mean:
                f[ind][ind_sub][ind_sub_sub]='B'
            elif element == d_mean:
                f[ind][ind_sub][ind_sub_sub]='C'
            elif element > d_mean and element < d_max:
                f[ind][ind_sub][ind_sub_sub]='D'
            else:
                f[ind][ind_sub][ind_sub_sub]='E'
print(f)

ValueError: invalid literal for int() with base 10: 'D'