In [2]:
#1. Import the NUMPY package under the name np.

import numpy as np


In [3]:
#2. Print the NUMPY version and the configuration.

print(np.version.version)



1.20.1


In [13]:
#3. Generate a 2x3x5 3-dimensional array with random values. 
# Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy 
# to generate random arrays. How many ways can you find?


# a = np.random.randint([1], high=[10], size=[2,3,5])
a = np.random.random((2,3,5))

In [14]:
#4. Print a.
print(a)

[[[0.29059606 0.6929675  0.11254451 0.75362656 0.73711237]
  [0.15508006 0.37035489 0.76033082 0.44564307 0.79875911]
  [0.83525413 0.28545796 0.02450158 0.34002752 0.46792019]]

 [[0.76935387 0.47058751 0.74303882 0.45697583 0.79376209]
  [0.57515287 0.41586711 0.10918473 0.47138571 0.63308642]
  [0.96153208 0.30717352 0.07529411 0.49382925 0.61408563]]]


In [51]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


b = np.ones([5,2,3])

In [52]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [53]:
#7. Do a and b have the same size? How do you prove that in Python code?

print('Do a and b have the same size?',np.size(a) == np.size(b))




Do a and b have the same size? True


In [54]:
#8. Are you able to add a and b? Why or why not?
try:
    a+b
except ValueError:
    print('Las dimensiones de las matrices deben coincidir')

Las dimensiones de las matrices deben coincidir


In [56]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
#5,2,3
c = np.transpose(b, (1,2,0))
c.shape


(2, 3, 5)

In [57]:
# 10. Try to add a and c. Now it should work. Assign the sum to varialbe 
# "d". But why does it work now?

d = a + c
print(d,'\n')
print('La forma de a:',np.shape(a),'es igual a la forma de c:',np.shape(c))

[[[1.29059606 1.6929675  1.11254451 1.75362656 1.73711237]
  [1.15508006 1.37035489 1.76033082 1.44564307 1.79875911]
  [1.83525413 1.28545796 1.02450158 1.34002752 1.46792019]]

 [[1.76935387 1.47058751 1.74303882 1.45697583 1.79376209]
  [1.57515287 1.41586711 1.10918473 1.47138571 1.63308642]
  [1.96153208 1.30717352 1.07529411 1.49382925 1.61408563]]] 

La forma de a: (2, 3, 5) es igual a la forma de c: (2, 3, 5)


In [58]:
#11. Print a and d. Notice the difference and relation of the 
# two array in terms of the values? Explain.

print('a = \n',a,'\n')
print('d = \n',d,'\n')
print('Al sumar a a una matriz de "unos", el valor de d es el valor de a + 1')


a = 
 [[[0.29059606 0.6929675  0.11254451 0.75362656 0.73711237]
  [0.15508006 0.37035489 0.76033082 0.44564307 0.79875911]
  [0.83525413 0.28545796 0.02450158 0.34002752 0.46792019]]

 [[0.76935387 0.47058751 0.74303882 0.45697583 0.79376209]
  [0.57515287 0.41586711 0.10918473 0.47138571 0.63308642]
  [0.96153208 0.30717352 0.07529411 0.49382925 0.61408563]]] 

d = 
 [[[1.29059606 1.6929675  1.11254451 1.75362656 1.73711237]
  [1.15508006 1.37035489 1.76033082 1.44564307 1.79875911]
  [1.83525413 1.28545796 1.02450158 1.34002752 1.46792019]]

 [[1.76935387 1.47058751 1.74303882 1.45697583 1.79376209]
  [1.57515287 1.41586711 1.10918473 1.47138571 1.63308642]
  [1.96153208 1.30717352 1.07529411 1.49382925 1.61408563]]] 

Al sumar a a una matriz de "unos", el valor de d es el valor de a + 1


In [59]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)

[[[0.29059606 0.6929675  0.11254451 0.75362656 0.73711237]
  [0.15508006 0.37035489 0.76033082 0.44564307 0.79875911]
  [0.83525413 0.28545796 0.02450158 0.34002752 0.46792019]]

 [[0.76935387 0.47058751 0.74303882 0.45697583 0.79376209]
  [0.57515287 0.41586711 0.10918473 0.47138571 0.63308642]
  [0.96153208 0.30717352 0.07529411 0.49382925 0.61408563]]]


In [60]:
#13. Does e equal to a? Why or why not?

print(e == a,'\n')

print('Cualquier numero multiplicado por uno es igual a ese numero. a * 1 = a')


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]] 

Cualquier numero multiplicado por uno es igual a ese numero. a * 1 = a


In [63]:
#14. Identify the max, min, and mean values in d. 
# Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print('max:',d_max,'\n')
print('min:',d_min,'\n')
print('mean:',d_mean)

max: 1.96153208326675 

min: 1.0245015761233 

mean: 1.4986828630427687


In [65]:
#15. Now we want to label the values in d. 

# First create an empty array "f" with the 
# same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))

array([[[0.29059606, 0.6929675 , 0.11254451, 0.75362656, 0.73711237],
        [0.15508006, 0.37035489, 0.76033082, 0.44564307, 0.79875911],
        [0.83525413, 0.28545796, 0.02450158, 0.34002752, 0.46792019]],

       [[0.76935387, 0.47058751, 0.74303882, 0.45697583, 0.79376209],
        [0.57515287, 0.41586711, 0.10918473, 0.47138571, 0.63308642],
        [0.96153208, 0.30717352, 0.07529411, 0.49382925, 0.61408563]]])

In [66]:
d

array([[[1.29059606, 1.6929675 , 1.11254451, 1.75362656, 1.73711237],
        [1.15508006, 1.37035489, 1.76033082, 1.44564307, 1.79875911],
        [1.83525413, 1.28545796, 1.02450158, 1.34002752, 1.46792019]],

       [[1.76935387, 1.47058751, 1.74303882, 1.45697583, 1.79376209],
        [1.57515287, 1.41586711, 1.10918473, 1.47138571, 1.63308642],
        [1.96153208, 1.30717352, 1.07529411, 1.49382925, 1.61408563]]])

In [81]:

# #16. Populate the values in f. For each value in d, 
# if it's larger than d_min but smaller than d_mean, 
# assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, 
# assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, 
# and 100. Note: you don't have to use Numpy in this question.

# f = np.where(d == d_min, 0,
#             np.where((d > d_min) & (d < d_mean), 25,
#                     np.where(d == d_mean, 50,
#                              np.where((d > d_mean) & (d < d_max), 75,10)
#                              )
#                     )
#             )
# f

for k in range(len(d)): # para cada tabla en el cubo
    for j in range(len(d[k])): # para cada fila en la tabla
        for i in range(len(d[k][j])): # para cada elemento en la fila
            
            # d[Tabla, Fila, Elemento]
            if d[k,j,i] > d_min and d[k,j,i] < d_mean:
                f[k,j,i] = 25
            elif d[k,j,i] > d_mean and d[k,j,i] < d_max:
                f[k,j,i] = 75
            elif d[k,j,i] == d_min:
                f[k,j,i] = 0
            elif d[k,j,i] == d_max:
                f[k,j,i] = 100
            else:
                f[k,j,i] = 50
                



In [82]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d,'\n',f)


[[[1.29059606 1.6929675  1.11254451 1.75362656 1.73711237]
  [1.15508006 1.37035489 1.76033082 1.44564307 1.79875911]
  [1.83525413 1.28545796 1.02450158 1.34002752 1.46792019]]

 [[1.76935387 1.47058751 1.74303882 1.45697583 1.79376209]
  [1.57515287 1.41586711 1.10918473 1.47138571 1.63308642]
  [1.96153208 1.30717352 1.07529411 1.49382925 1.61408563]]] 
 [[[ 25  75  25  75  75]
  [ 25  25  75  25  75]
  [ 75  25   0  25  25]]

 [[ 75  25  75  25  75]
  [ 75  25  25  25  75]
  [100  25  25  25  75]]]


In [80]:

# #18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],

#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.

g = np.empty((2,3,5), dtype='O')

for k in range(len(d)): # para cada tabla en el cubo
    for j in range(len(d[k])): # para cada fila en la tabla
        for i in range(len(d[k][j])): # para cada elemento en la fila
            
            # d[Tabla, Fila, Elemento]
            if d[k,j,i] > d_min and d[k,j,i] < d_mean:
                g[k,j,i] = 'B'
            elif d[k,j,i] > d_mean and d[k,j,i] < d_max:
                g[k,j,i] = 'D'
            elif d[k,j,i] == d_min:
                g[k,j,i] = 'A'
            elif d[k,j,i] == d_max:
                g[k,j,i] = 'E'
            else:
                g[k,j,i] = 'C'
                
print(d,'\n\n',g)


[[[1.29059606 1.6929675  1.11254451 1.75362656 1.73711237]
  [1.15508006 1.37035489 1.76033082 1.44564307 1.79875911]
  [1.83525413 1.28545796 1.02450158 1.34002752 1.46792019]]

 [[1.76935387 1.47058751 1.74303882 1.45697583 1.79376209]
  [1.57515287 1.41586711 1.10918473 1.47138571 1.63308642]
  [1.96153208 1.30717352 1.07529411 1.49382925 1.61408563]]] 

 [[['B' 'D' 'B' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'A' 'B' 'B']]

 [['D' 'B' 'D' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['E' 'B' 'B' 'B' 'D']]]
