In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.__version__

'1.22.3'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.rand(2,3,5)

In [4]:
#4. Print a.
print(a)

[[[0.65346535 0.77922074 0.00915332 0.67096213 0.27904716]
  [0.81383177 0.00353518 0.46102917 0.33563722 0.25123702]
  [0.95831437 0.43280675 0.97907397 0.6512118  0.52326049]]

 [[0.94340955 0.90451434 0.51632969 0.8565192  0.7677092 ]
  [0.25396023 0.05290118 0.08927254 0.5248678  0.68914067]
  [0.22630599 0.13486764 0.86880563 0.46490608 0.65905858]]]


In [32]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))

In [33]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [34]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size == b.size) #we compare with the atribute size

True


In [35]:
#8. Are you able to add a and b? Why or why not?
a + b #we can't add a and b because they haven't the same dimension

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [39]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose()
c = c.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [40]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c #it works because they have the same dimension
print(d)

[[[1.65346535 1.77922074 1.00915332 1.67096213 1.27904716]
  [1.81383177 1.00353518 1.46102917 1.33563722 1.25123702]
  [1.95831437 1.43280675 1.97907397 1.6512118  1.52326049]]

 [[1.94340955 1.90451434 1.51632969 1.8565192  1.7677092 ]
  [1.25396023 1.05290118 1.08927254 1.5248678  1.68914067]
  [1.22630599 1.13486764 1.86880563 1.46490608 1.65905858]]]


In [41]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a) #the values in a are between 0 and 1, and the values in b are between 1 and 2

[[[0.65346535 0.77922074 0.00915332 0.67096213 0.27904716]
  [0.81383177 0.00353518 0.46102917 0.33563722 0.25123702]
  [0.95831437 0.43280675 0.97907397 0.6512118  0.52326049]]

 [[0.94340955 0.90451434 0.51632969 0.8565192  0.7677092 ]
  [0.25396023 0.05290118 0.08927254 0.5248678  0.68914067]
  [0.22630599 0.13486764 0.86880563 0.46490608 0.65905858]]]


In [42]:
print(d)

[[[1.65346535 1.77922074 1.00915332 1.67096213 1.27904716]
  [1.81383177 1.00353518 1.46102917 1.33563722 1.25123702]
  [1.95831437 1.43280675 1.97907397 1.6512118  1.52326049]]

 [[1.94340955 1.90451434 1.51632969 1.8565192  1.7677092 ]
  [1.25396023 1.05290118 1.08927254 1.5248678  1.68914067]
  [1.22630599 1.13486764 1.86880563 1.46490608 1.65905858]]]


In [43]:
#12. Multiply a and c. Assign the result to e.
e = a * c
print(e)

[[[0.65346535 0.77922074 0.00915332 0.67096213 0.27904716]
  [0.81383177 0.00353518 0.46102917 0.33563722 0.25123702]
  [0.95831437 0.43280675 0.97907397 0.6512118  0.52326049]]

 [[0.94340955 0.90451434 0.51632969 0.8565192  0.7677092 ]
  [0.25396023 0.05290118 0.08927254 0.5248678  0.68914067]
  [0.22630599 0.13486764 0.86880563 0.46490608 0.65905858]]]


In [44]:
#13. Does e equal to a? Why or why not?
print(a) #yes, a and e are equal because we multiplied a * 1

[[[0.65346535 0.77922074 0.00915332 0.67096213 0.27904716]
  [0.81383177 0.00353518 0.46102917 0.33563722 0.25123702]
  [0.95831437 0.43280675 0.97907397 0.6512118  0.52326049]]

 [[0.94340955 0.90451434 0.51632969 0.8565192  0.7677092 ]
  [0.25396023 0.05290118 0.08927254 0.5248678  0.68914067]
  [0.22630599 0.13486764 0.86880563 0.46490608 0.65905858]]]


In [45]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
#d_max = np.max(d)
#print(d_min = np.min(d))
#print(d_mean = np.mean(d))
d_mean = d.mean()
d_max = d.max()
d_min = d.min()

In [46]:
print(d_mean)
print(d_max)
print(d_min)

1.5251451584956897
1.9790739719137793
1.003535181941633


In [47]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape 
#(i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))

In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""""

In [48]:
#f = np.where(d == d_min,0, np.where((d > d_min) & (d < d_mean),25, np.where (d == d_mean,50, np.where((d > d_mean) & (d < d_max),75, 100))))
f= np.where(d==d_min, 0, np.where(d == d_max, 100, np.where(d == d_mean, 50,np.where((d_min < d) & (d<d_mean), 25, np.where((d_mean < d) & (d<d_max), 75, 1000)))))

In [ ]:
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [49]:
print(d)
print(f)

[[[1.65346535 1.77922074 1.00915332 1.67096213 1.27904716]
  [1.81383177 1.00353518 1.46102917 1.33563722 1.25123702]
  [1.95831437 1.43280675 1.97907397 1.6512118  1.52326049]]

 [[1.94340955 1.90451434 1.51632969 1.8565192  1.7677092 ]
  [1.25396023 1.05290118 1.08927254 1.5248678  1.68914067]
  [1.22630599 1.13486764 1.86880563 1.46490608 1.65905858]]]
[[[ 75  75  25  75  25]
  [ 75   0  25  25  25]
  [ 75  25 100  75  25]]

 [[ 75  75  25  75  75]
  [ 25  25  25  25  75]
  [ 25  25  75  25  75]]]
