In [1]:
import numpy as np



In [2]:
print(np.__version__)

1.20.3


In [3]:
a = np.random.random((2, 3, 5))
a

array([[[0.13329756, 0.5823677 , 0.96953359, 0.68871978, 0.65398872],
        [0.09051965, 0.15355781, 0.77622011, 0.62158726, 0.77177673],
        [0.81625384, 0.76462003, 0.20858417, 0.1774428 , 0.35268322]],

       [[0.15052192, 0.74583413, 0.37077635, 0.64535597, 0.19305099],
        [0.8368861 , 0.30734192, 0.13788951, 0.7600662 , 0.17059466],
        [0.91982367, 0.37578986, 0.84129594, 0.04624852, 0.3532916 ]]])

In [4]:
print(a)

[[[0.13329756 0.5823677  0.96953359 0.68871978 0.65398872]
  [0.09051965 0.15355781 0.77622011 0.62158726 0.77177673]
  [0.81625384 0.76462003 0.20858417 0.1774428  0.35268322]]

 [[0.15052192 0.74583413 0.37077635 0.64535597 0.19305099]
  [0.8368861  0.30734192 0.13788951 0.7600662  0.17059466]
  [0.91982367 0.37578986 0.84129594 0.04624852 0.3532916 ]]]


In [5]:
b = np.ones((5, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
a.size==b.size

True

In [8]:
a+b # No se pueden sumar porque no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [9]:
b.reshape(2,3,5)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
c=b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [11]:
d=a+c #Ahora si se pueden sumar porque tienen la misma forma. 

In [12]:
print(a)

print(d)
#La diferencia de valor entre a y c es que a a le sumaron todos los unos contenidos en la matriz c. 

[[[0.13329756 0.5823677  0.96953359 0.68871978 0.65398872]
  [0.09051965 0.15355781 0.77622011 0.62158726 0.77177673]
  [0.81625384 0.76462003 0.20858417 0.1774428  0.35268322]]

 [[0.15052192 0.74583413 0.37077635 0.64535597 0.19305099]
  [0.8368861  0.30734192 0.13788951 0.7600662  0.17059466]
  [0.91982367 0.37578986 0.84129594 0.04624852 0.3532916 ]]]
[[[1.13329756 1.5823677  1.96953359 1.68871978 1.65398872]
  [1.09051965 1.15355781 1.77622011 1.62158726 1.77177673]
  [1.81625384 1.76462003 1.20858417 1.1774428  1.35268322]]

 [[1.15052192 1.74583413 1.37077635 1.64535597 1.19305099]
  [1.8368861  1.30734192 1.13788951 1.7600662  1.17059466]
  [1.91982367 1.37578986 1.84129594 1.04624852 1.3532916 ]]]


In [13]:
e= a*c
print(e)

[[[0.13329756 0.5823677  0.96953359 0.68871978 0.65398872]
  [0.09051965 0.15355781 0.77622011 0.62158726 0.77177673]
  [0.81625384 0.76462003 0.20858417 0.1774428  0.35268322]]

 [[0.15052192 0.74583413 0.37077635 0.64535597 0.19305099]
  [0.8368861  0.30734192 0.13788951 0.7600662  0.17059466]
  [0.91982367 0.37578986 0.84129594 0.04624852 0.3532916 ]]]


In [14]:
#Todos los valores de e son iguales a los de a porque a fue multiplicado sólo por 1

a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [15]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.969533594906581
1.0462485164924635
1.4871973436636632


In [16]:
f = np.empty((2,3,5))
print(f)

[[[0.13329756 0.5823677  0.96953359 0.68871978 0.65398872]
  [0.09051965 0.15355781 0.77622011 0.62158726 0.77177673]
  [0.81625384 0.76462003 0.20858417 0.1774428  0.35268322]]

 [[0.15052192 0.74583413 0.37077635 0.64535597 0.19305099]
  [0.8368861  0.30734192 0.13788951 0.7600662  0.17059466]
  [0.91982367 0.37578986 0.84129594 0.04624852 0.3532916 ]]]


In [21]:
f = np.where((d > d_min) & (d < d_mean), 25,
         np.where((d > d_mean) & (d < d_max), 75,
                   np.where(d == d_mean, 50,
                             np.where(d == d_min, 0,
                                       np.where(d == d_max, 100,
                                               100)))))



array([[[ 25,  75, 100,  75,  75],
        [ 25,  25,  75,  75,  75],
        [ 75,  75,  25,  25,  25]],

       [[ 25,  75,  25,  75,  25],
        [ 75,  25,  25,  75,  25],
        [ 75,  25,  75,   0,  25]]])

In [23]:
f = np.where((d > d_min) & (d < d_mean), 'D',
         np.where((d > d_mean) & (d < d_max), 'C',
                   np.where(d == d_mean, 'T',
                             np.where(d == d_min, 'Y',
                                       np.where(d == d_max, 'L',
                                               100)))))

f


array([[['D', 'C', 'L', 'C', 'C'],
        ['D', 'D', 'C', 'C', 'C'],
        ['C', 'C', 'D', 'D', 'D']],

       [['D', 'C', 'D', 'C', 'D'],
        ['C', 'D', 'D', 'C', 'D'],
        ['C', 'D', 'C', 'Y', 'D']]], dtype='<U11')