In [1]:
#1
import numpy as np

In [2]:
#2
np.show_config()

openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', 

In [3]:
#2
np.__version__

'1.22.3'

In [4]:
#3
a = np.random.random((2,3,5))

In [5]:
#4
print(a)

[[[0.29617398 0.6074968  0.58972636 0.5980548  0.69324493]
  [0.63150155 0.13587963 0.6919149  0.03269467 0.14141103]
  [0.91108152 0.41407368 0.49974495 0.9350408  0.31023251]]

 [[0.85499473 0.51474252 0.59887048 0.90810704 0.75233991]
  [0.50913223 0.39139519 0.64233344 0.2566372  0.67972043]
  [0.84579978 0.77086475 0.94163802 0.67081747 0.24363611]]]


In [6]:
#5
b = np.ones((5,3,2))

In [7]:
#6
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [8]:
#7
np.size(a) == np.size(b)

True

In [9]:
#8
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [10]:
#9
c = np.transpose(b)

In [11]:
#10
d = a + c

In [12]:
#11
print(a)
print(d)

# Los valores de d son a+1

[[[0.29617398 0.6074968  0.58972636 0.5980548  0.69324493]
  [0.63150155 0.13587963 0.6919149  0.03269467 0.14141103]
  [0.91108152 0.41407368 0.49974495 0.9350408  0.31023251]]

 [[0.85499473 0.51474252 0.59887048 0.90810704 0.75233991]
  [0.50913223 0.39139519 0.64233344 0.2566372  0.67972043]
  [0.84579978 0.77086475 0.94163802 0.67081747 0.24363611]]]
[[[1.29617398 1.6074968  1.58972636 1.5980548  1.69324493]
  [1.63150155 1.13587963 1.6919149  1.03269467 1.14141103]
  [1.91108152 1.41407368 1.49974495 1.9350408  1.31023251]]

 [[1.85499473 1.51474252 1.59887048 1.90810704 1.75233991]
  [1.50913223 1.39139519 1.64233344 1.2566372  1.67972043]
  [1.84579978 1.77086475 1.94163802 1.67081747 1.24363611]]]


In [13]:
#12
e = a * c

In [14]:
#13
e == a

#Porque está multiplicando los valores por 1, a*1=e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [15]:
#14
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_min, d_mean, d_max)

1.0326946687620666 1.5689767138889803 1.9416380209945308


In [16]:
#15
f = np.empty((2,3,5))

In [17]:
#16

shape_d = d.shape

for matriz in range(shape_d[0]):
    for vector in range(shape_d[1]):
        for valor in range(shape_d[2]):
            if d[matriz,vector,valor] == d_min:
                f[matriz,vector,valor] = 0
            elif d[matriz,vector,valor] < d_mean:
                f[matriz,vector,valor] = 25
            elif d[matriz,vector,valor] == d_mean:
                f[matriz,vector,valor] = 50
            elif d[matriz,vector,valor] < d_max:
                f[matriz,vector,valor] = 75
            elif d[matriz,vector,valor] == d_max:
                f[matriz,vector,valor] = 100
print (f)

[[[ 25.  75.  75.  75.  75.]
  [ 75.  25.  75.   0.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75. 100.  75.  25.]]]


In [18]:
#17

print(d)
print(f)

[[[1.29617398 1.6074968  1.58972636 1.5980548  1.69324493]
  [1.63150155 1.13587963 1.6919149  1.03269467 1.14141103]
  [1.91108152 1.41407368 1.49974495 1.9350408  1.31023251]]

 [[1.85499473 1.51474252 1.59887048 1.90810704 1.75233991]
  [1.50913223 1.39139519 1.64233344 1.2566372  1.67972043]
  [1.84579978 1.77086475 1.94163802 1.67081747 1.24363611]]]
[[[ 25.  75.  75.  75.  75.]
  [ 75.  25.  75.   0.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75. 100.  75.  25.]]]


In [20]:
g = np.empty((2,3,5), dtype='S')
print(g)

for matriz in range(shape_d[0]):
    for vector in range(shape_d[1]):
        for valor in range(shape_d[2]):
            if d[matriz,vector,valor] == d_min:
                g[matriz,vector,valor] = 'A'
            elif d[matriz,vector,valor] < d_mean:
                g[matriz,vector,valor] = 'B'
            elif d[matriz,vector,valor] == d_mean:
                g[matriz,vector,valor] = 'C'
            elif d[matriz,vector,valor] < d_max:
                g[matriz,vector,valor] = 'D'
            elif d[matriz,vector,valor] == d_max:
                g[matriz,vector,valor] = 'E'
print (g)

[[[b'' b'' b'' b'' b'']
  [b'' b'' b'' b'\xa0' b'V']
  [b'\xf4' b'\x0e' b'\xc5' b'\x01' b'']]

 [[b'' b'\xa0' b'T' b'\xf4' b'\x0e']
  [b'\xc5' b'\x01' b'' b'' b'\xe0']
  [b'U' b'\xf4' b'\x0e' b'\xc5' b'\x01']]]
[[[b'B' b'D' b'D' b'D' b'D']
  [b'D' b'B' b'D' b'A' b'B']
  [b'D' b'B' b'B' b'D' b'B']]

 [[b'D' b'B' b'D' b'D' b'D']
  [b'B' b'B' b'D' b'B' b'D']
  [b'D' b'D' b'E' b'D' b'B']]]
